API_KEY = "12345-ABCDE-67890-FGHIJ"  # Example API key
DATABASE_PASSWORD = "superSecretPassword123"  # Database password
PRIVATE_KEY = """
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA1hx7/EOKCjZ8S5V+uG/PAHtMHZAX6ABKXJXc2AcP8jP8s2YY
uPtC11kCZpe5SpT4LBtFj3EN9u5W/Z4cMLW9IQ+KZgZZFp6KPTxoPvJ92uHeWrCb
xQED1twwiAXRT4oaFb1CJSh8Ytrn0OjZ4PkVAGcTPAfUdJ/NXvO7THKyrVz8Hxl8
...
-----END RSA PRIVATE KEY-----
"""  # Private key

print(f"Using API Key: {API_KEY}")